# SPDX-FileCopyrightText: Copyright 2026 NXP
# SPDX-License-Identifier: Apache-2.0

CONFIG_EBPF=y
CONFIG_EBPF_PM=y
CONFIG_EBPF_STATS=y
CONFIG_PM=y
CONFIG_TICKLESS_KERNEL=y
CONFIG_MAIN_STACK_SIZE=3072
CONFIG_IDLE_STACK_SIZE=1024