/*
 * SPDX-FileCopyrightText: Copyright 2026 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief Internal eBPF low-level instruction opcode definitions.
 *
 * @note Visibility: eBPF subsystem internals only; not exposed to applications.
 */

#ifndef ZEPHYR_SUBSYS_EBPF_INSN_EBPF_INSN_BASIC_H_
#define ZEPHYR_SUBSYS_EBPF_INSN_EBPF_INSN_BASIC_H_

#ifdef __cplusplus
extern "C" {
#endif

#define EBPF_CLS_LD		0x00U
#define EBPF_CLS_LDX		0x01U
#define EBPF_CLS_ST		0x02U
#define EBPF_CLS_STX		0x03U
#define EBPF_CLS_ALU		0x04U
#define EBPF_CLS_JMP		0x05U
#define EBPF_CLS_ALU64		0x07U

#define EBPF_SRC_IMM		0x00U
#define EBPF_SRC_REG		0x08U

#define EBPF_ALU_ADD		0x00U
#define EBPF_ALU_SUB		0x10U
#define EBPF_ALU_MUL		0x20U
#define EBPF_ALU_DIV		0x30U
#define EBPF_ALU_OR		0x40U
#define EBPF_ALU_AND		0x50U
#define EBPF_ALU_LSH		0x60U
#define EBPF_ALU_RSH		0x70U
#define EBPF_ALU_NEG		0x80U
#define EBPF_ALU_MOD		0x90U
#define EBPF_ALU_XOR		0xA0U
#define EBPF_ALU_MOV		0xB0U

#define EBPF_JMP_JA		0x00U
#define EBPF_JMP_JEQ		0x10U
#define EBPF_JMP_JGT		0x20U
#define EBPF_JMP_JGE		0x30U
#define EBPF_JMP_JSET		0x40U
#define EBPF_JMP_JNE		0x50U
#define EBPF_JMP_JLT		0xA0U
#define EBPF_JMP_JLE		0xB0U
#define EBPF_JMP_CALL		0x80U
#define EBPF_JMP_EXIT		0x90U

#define EBPF_SIZE_W		0x00U
#define EBPF_SIZE_H		0x08U
#define EBPF_SIZE_B		0x10U
#define EBPF_SIZE_DW		0x18U

#define EBPF_MODE_IMM		0x00U
#define EBPF_MODE_MEM		0x60U

#define EBPF_PSEUDO_MAP_FD	0x01U

#define EBPF_OP_ADD64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_ADD | EBPF_SRC_IMM)
#define EBPF_OP_ADD64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_ADD | EBPF_SRC_REG)
#define EBPF_OP_SUB64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_SUB | EBPF_SRC_IMM)
#define EBPF_OP_SUB64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_SUB | EBPF_SRC_REG)
#define EBPF_OP_MUL64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_MUL | EBPF_SRC_IMM)
#define EBPF_OP_MUL64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_MUL | EBPF_SRC_REG)
#define EBPF_OP_DIV64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_DIV | EBPF_SRC_IMM)
#define EBPF_OP_DIV64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_DIV | EBPF_SRC_REG)
#define EBPF_OP_OR64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_OR  | EBPF_SRC_IMM)
#define EBPF_OP_OR64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_OR  | EBPF_SRC_REG)
#define EBPF_OP_AND64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_AND | EBPF_SRC_IMM)
#define EBPF_OP_AND64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_AND | EBPF_SRC_REG)
#define EBPF_OP_LSH64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_LSH | EBPF_SRC_IMM)
#define EBPF_OP_LSH64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_LSH | EBPF_SRC_REG)
#define EBPF_OP_RSH64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_RSH | EBPF_SRC_IMM)
#define EBPF_OP_RSH64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_RSH | EBPF_SRC_REG)
#define EBPF_OP_NEG64		(EBPF_CLS_ALU64 | EBPF_ALU_NEG | EBPF_SRC_IMM)
#define EBPF_OP_MOD64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_MOD | EBPF_SRC_IMM)
#define EBPF_OP_MOD64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_MOD | EBPF_SRC_REG)
#define EBPF_OP_XOR64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_XOR | EBPF_SRC_IMM)
#define EBPF_OP_XOR64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_XOR | EBPF_SRC_REG)
#define EBPF_OP_MOV64_IMM	(EBPF_CLS_ALU64 | EBPF_ALU_MOV | EBPF_SRC_IMM)
#define EBPF_OP_MOV64_REG	(EBPF_CLS_ALU64 | EBPF_ALU_MOV | EBPF_SRC_REG)

#define EBPF_OP_ADD_IMM		(EBPF_CLS_ALU | EBPF_ALU_ADD | EBPF_SRC_IMM)
#define EBPF_OP_ADD_REG		(EBPF_CLS_ALU | EBPF_ALU_ADD | EBPF_SRC_REG)
#define EBPF_OP_SUB_IMM		(EBPF_CLS_ALU | EBPF_ALU_SUB | EBPF_SRC_IMM)
#define EBPF_OP_SUB_REG		(EBPF_CLS_ALU | EBPF_ALU_SUB | EBPF_SRC_REG)
#define EBPF_OP_MUL_IMM		(EBPF_CLS_ALU | EBPF_ALU_MUL | EBPF_SRC_IMM)
#define EBPF_OP_MUL_REG		(EBPF_CLS_ALU | EBPF_ALU_MUL | EBPF_SRC_REG)
#define EBPF_OP_DIV_IMM		(EBPF_CLS_ALU | EBPF_ALU_DIV | EBPF_SRC_IMM)
#define EBPF_OP_DIV_REG		(EBPF_CLS_ALU | EBPF_ALU_DIV | EBPF_SRC_REG)
#define EBPF_OP_OR_IMM		(EBPF_CLS_ALU | EBPF_ALU_OR  | EBPF_SRC_IMM)
#define EBPF_OP_OR_REG		(EBPF_CLS_ALU | EBPF_ALU_OR  | EBPF_SRC_REG)
#define EBPF_OP_AND_IMM		(EBPF_CLS_ALU | EBPF_ALU_AND | EBPF_SRC_IMM)
#define EBPF_OP_AND_REG		(EBPF_CLS_ALU | EBPF_ALU_AND | EBPF_SRC_REG)
#define EBPF_OP_LSH_IMM		(EBPF_CLS_ALU | EBPF_ALU_LSH | EBPF_SRC_IMM)
#define EBPF_OP_LSH_REG		(EBPF_CLS_ALU | EBPF_ALU_LSH | EBPF_SRC_REG)
#define EBPF_OP_RSH_IMM		(EBPF_CLS_ALU | EBPF_ALU_RSH | EBPF_SRC_IMM)
#define EBPF_OP_RSH_REG		(EBPF_CLS_ALU | EBPF_ALU_RSH | EBPF_SRC_REG)
#define EBPF_OP_NEG		(EBPF_CLS_ALU | EBPF_ALU_NEG | EBPF_SRC_IMM)
#define EBPF_OP_MOD_IMM		(EBPF_CLS_ALU | EBPF_ALU_MOD | EBPF_SRC_IMM)
#define EBPF_OP_MOD_REG		(EBPF_CLS_ALU | EBPF_ALU_MOD | EBPF_SRC_REG)
#define EBPF_OP_XOR_IMM		(EBPF_CLS_ALU | EBPF_ALU_XOR | EBPF_SRC_IMM)
#define EBPF_OP_XOR_REG		(EBPF_CLS_ALU | EBPF_ALU_XOR | EBPF_SRC_REG)
#define EBPF_OP_MOV_IMM		(EBPF_CLS_ALU | EBPF_ALU_MOV | EBPF_SRC_IMM)
#define EBPF_OP_MOV_REG		(EBPF_CLS_ALU | EBPF_ALU_MOV | EBPF_SRC_REG)

#define EBPF_OP_LD_IMM_DW	(EBPF_CLS_LD  | EBPF_SIZE_DW | EBPF_MODE_IMM)
#define EBPF_OP_LDX_B		(EBPF_CLS_LDX | EBPF_SIZE_B  | EBPF_MODE_MEM)
#define EBPF_OP_LDX_H		(EBPF_CLS_LDX | EBPF_SIZE_H  | EBPF_MODE_MEM)
#define EBPF_OP_LDX_W		(EBPF_CLS_LDX | EBPF_SIZE_W  | EBPF_MODE_MEM)
#define EBPF_OP_LDX_DW		(EBPF_CLS_LDX | EBPF_SIZE_DW | EBPF_MODE_MEM)
#define EBPF_OP_STX_B		(EBPF_CLS_STX | EBPF_SIZE_B  | EBPF_MODE_MEM)
#define EBPF_OP_STX_H		(EBPF_CLS_STX | EBPF_SIZE_H  | EBPF_MODE_MEM)
#define EBPF_OP_STX_W		(EBPF_CLS_STX | EBPF_SIZE_W  | EBPF_MODE_MEM)
#define EBPF_OP_STX_DW		(EBPF_CLS_STX | EBPF_SIZE_DW | EBPF_MODE_MEM)
#define EBPF_OP_ST_B		(EBPF_CLS_ST  | EBPF_SIZE_B  | EBPF_MODE_MEM)
#define EBPF_OP_ST_H		(EBPF_CLS_ST  | EBPF_SIZE_H  | EBPF_MODE_MEM)
#define EBPF_OP_ST_W		(EBPF_CLS_ST  | EBPF_SIZE_W  | EBPF_MODE_MEM)
#define EBPF_OP_ST_DW		(EBPF_CLS_ST  | EBPF_SIZE_DW | EBPF_MODE_MEM)

#define EBPF_OP_JA		(EBPF_CLS_JMP | EBPF_JMP_JA)
#define EBPF_OP_JEQ_IMM		(EBPF_CLS_JMP | EBPF_JMP_JEQ  | EBPF_SRC_IMM)
#define EBPF_OP_JEQ_REG		(EBPF_CLS_JMP | EBPF_JMP_JEQ  | EBPF_SRC_REG)
#define EBPF_OP_JGT_IMM		(EBPF_CLS_JMP | EBPF_JMP_JGT  | EBPF_SRC_IMM)
#define EBPF_OP_JGT_REG		(EBPF_CLS_JMP | EBPF_JMP_JGT  | EBPF_SRC_REG)
#define EBPF_OP_JGE_IMM		(EBPF_CLS_JMP | EBPF_JMP_JGE  | EBPF_SRC_IMM)
#define EBPF_OP_JGE_REG		(EBPF_CLS_JMP | EBPF_JMP_JGE  | EBPF_SRC_REG)
#define EBPF_OP_JSET_IMM	(EBPF_CLS_JMP | EBPF_JMP_JSET | EBPF_SRC_IMM)
#define EBPF_OP_JSET_REG	(EBPF_CLS_JMP | EBPF_JMP_JSET | EBPF_SRC_REG)
#define EBPF_OP_JNE_IMM		(EBPF_CLS_JMP | EBPF_JMP_JNE  | EBPF_SRC_IMM)
#define EBPF_OP_JNE_REG		(EBPF_CLS_JMP | EBPF_JMP_JNE  | EBPF_SRC_REG)
#define EBPF_OP_JLT_IMM		(EBPF_CLS_JMP | EBPF_JMP_JLT  | EBPF_SRC_IMM)
#define EBPF_OP_JLT_REG		(EBPF_CLS_JMP | EBPF_JMP_JLT  | EBPF_SRC_REG)
#define EBPF_OP_JLE_IMM		(EBPF_CLS_JMP | EBPF_JMP_JLE  | EBPF_SRC_IMM)
#define EBPF_OP_JLE_REG		(EBPF_CLS_JMP | EBPF_JMP_JLE  | EBPF_SRC_REG)
#define EBPF_OP_CALL		(EBPF_CLS_JMP | EBPF_JMP_CALL)
#define EBPF_OP_EXIT		(EBPF_CLS_JMP | EBPF_JMP_EXIT)

#define EBPF_CLASS_MASK		0x07U
#define EBPF_INSN_CLASS(opcode)	((opcode) & EBPF_CLASS_MASK)

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_SUBSYS_EBPF_INSN_EBPF_INSN_BASIC_H_ */
