# SPDX-FileCopyrightText: Copyright 2026 NXP
# SPDX-License-Identifier: Apache-2.0

CONFIG_EBPF=y
CONFIG_EBPF_LOADER=y
CONFIG_EBPF_TRACING=y
CONFIG_TRACING=y
CONFIG_TRACING_USER=y

CONFIG_NET_BUF=y
CONFIG_ZCBOR=y

CONFIG_MCUMGR=y
CONFIG_MCUMGR_GRP_EBPF=y
CONFIG_UART_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_UART=y
CONFIG_BASE64=y
CONFIG_CRC=y

CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=3072
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=3072
CONFIG_IDLE_STACK_SIZE=1024